const tableData2 = [
  {
    id: 1,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
  {
    id: 2,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
  {
    id: 3,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
  {
    id: 4,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
  {
    id: 5,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
  {
    id: 6,
    value: [{
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    },
    {
      Code: "First",
      Description: "Value",
      ALL1: "Value",
      ALL2: "Value",
      w32: "Value",
      w46: "Value",
      w61: "Value",
      w76: "Value",
      w91: "Value",
      w107: "Value",
      w127: "Value",
      w146: "Value",
      ALL3: "Value",
    }
  ]
  },
];

export default tableData2;
