const tableData1 = [
  {
    id: 1,
    value: {
      First: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
  {
    id: 2,
    value: {
      Second: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
  {
    id: 3,
    value: {
      Third: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
  {
    id: 4,
    value: {
      Fourth: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
  {
    id: 5,
    value: {
      Fifth: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
  {
    id: 6,
    value: {
      Sixth: "Value",
      B: "Value",
      C: "Value",
      D: "Male",
      E: "Value",
      G: "Value",
      H: "Value",
      I: "Value",
      L: "Value",
      M: "Value",
      N: "Value",
      P: "Value",
      Q: "Value",
      R: "Value",
      S: "Value",
    }
  },
];

export default tableData1;
